version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api-smtp

  api-smtp:
    image: ghcr.io/hnrobert/api-smtp:latest
    # build:
    #     context: src/
    #     dockerfile: docker/Dockerfile
    container_name: api-smtp
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    volumes:
      - ./data:/app/data
      - ./src/app/smtp_config.json:/app/smtp_config.json:ro
    expose:
      - '8000'

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - '127.0.0.1:1080:1080'
      - '127.0.0.1:1025:1025'
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc
    container_name: minio-client
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      /usr/bin/mc mb -p myminio/emails"
    depends_on:
      - minio

volumes:
  minio_data:
